### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by AbdallahAmmar96** [FACG6/enhance-a-smile#7]
## User Stories
- [ ] As a user, I want to read about how the service works and their vision.
- [ ] As a user, I want to find the donating section easily.
- [ ] As a user, I want to provide my personal information.
- [ ] As a user, I want to provide my donation information.
- [ ] As a user, I want to receive confirmation about my donation. 
- [ ] As a user, I want to find the request section easily.
- [ ] As a user, I want to provide as less as possible personal information for my request.
- [ ] As a user, I want to provide my request information.
- [ ] As a user, I want to receive confirmation about my request.
- [ ] As a user, I want to contact the owners and receive a response.
- [ ] As a user, I want to register for the news feed.
---
## Admin Stories
- [ ] As an admin, I want to login to the dashboard.
- [ ] As an admin, I want to keep track of donations.
- [ ] As an admin, I want to keep track of requests.
- [ ] As an admin, I want to edit my information in the settings.
